Cb 18
axrs/centrebull pull request #19
Opened 2017-02-22 11:19 UTC by CalebMacdonaldBlack

2017-02-22 12:09 UTC, lrobert142 submitted a review, later dismissed
See comments

2017-02-22 12:09 UTC, lrobert142 commented on resources/migrations/20170222203502-aggregates.up.sql
> +  activities  UUID REFERENCES activities (id)
Type required to be a postgres Array type

2017-02-23 22:20 UTC, axrs requested changes

2017-02-23 22:20 UTC, axrs commented on resources/migrations/20170222203502-aggregates.up.sql
> +  activities  UUID REFERENCES activities (id)
Correct. A single aggregate is a combination of multiple activities. Hence an array type :D

2017-03-01 09:01 UTC, CalebMacdonaldBlack commented
@axrs

2017-03-01 09:02 UTC, axrs approved these changes

2017-03-01 09:03 UTC, merged