Cb 26
axrs/centrebull pull request #25
Opened 2017-03-01 12:09 UTC by CalebMacdonaldBlack

2017-03-02 04:51 UTC, axrs requested changes

2017-03-02 04:51 UTC, axrs commented on test/clj/centrebull/test/db/ranges.clj
> +    (is (= range em))
Swap the order of these values for comparision.

They typical order in clojure (to have it reflect correctly in intelliJ ) on error is : expected then actual

2017-03-02 04:51 UTC, axrs commented on test/clj/centrebull/test/mock_generators.clj
> +  ([] (gen-range (rand-int 99999)))
This should be generating a uuid. Have a look at the competition generator (may require merging develop into this branch to get the function)

2017-03-02 04:51 UTC, axrs commented on test/clj/centrebull/test/db/ranges.clj
> +    (is (= range em))
It's not a major thing, but it's something I'm working to enforce where I see it. (and trying to use myself).

2017-03-02 05:26 UTC, CalebMacdonaldBlack commented
@axrs

2017-03-07 09:45 UTC, axrs approved these changes

2017-03-07 09:45 UTC, merged