Cb 27
axrs/centrebull pull request #26
Opened 2017-03-02 07:56 UTC by CalebMacdonaldBlack

2017-03-07 09:48 UTC, axrs requested changes

2017-03-07 09:48 UTC, axrs commented on src/cljc/centrebull/spec.cljc
> +    :req [:range/id]))
There's no spec defined for :range/id `(s/def :range/id is-uuid?)`

2017-03-07 09:48 UTC, axrs commented on test/clj/centrebull/test/ranges/core.clj
> +  (testing "ranges-delete!"
Add a new line above this. Seperates the tests making it a tad more readable.

2017-03-07 09:48 UTC, axrs commented on test/clj/centrebull/test/ranges/routes.clj
> +  (testing "Delete Range Route"
New line above for readability

2017-03-07 11:22 UTC, CalebMacdonaldBlack commented
@axrs

2017-03-08 08:03 UTC, axrs approved these changes

2017-03-08 08:09 UTC, merged