Cb 45
axrs/centrebull pull request #40
Opened 2017-03-18 07:22 UTC by CalebMacdonaldBlack

2017-03-18 07:23 UTC, CalebMacdonaldBlack commented on src/cljc/centrebull/spec.cljc
> +(defn- str->int [s] #?(:cljs (cond (and (string? s) #(not= "" %)) s
I was getting `Uncaught TypeError: Cannot read property 'reader' of undefined`. I don't completely understand what this function does but it works with this change

2017-03-18 07:26 UTC, CalebMacdonaldBlack commented on src/cljs/centrebull/shooters/view.cljs
> +        [:div {:local "1/3"} (if (empty? preferred-name) (str first-name " " last-name) preferred-name)]
Uncaught TypeError: Cannot read property 'reader' of undefined

2017-03-18 08:54 UTC, CalebMacdonaldBlack commented on src/less/_variables.less
> +@primary: indianred;
I like this look. What do you think?

2017-03-20 09:13 UTC, axrs commented on src/cljc/centrebull/spec.cljc
> +(defn- str->int [s] #?(:cljs (cond (and (string? s) #(not= "" %)) s
The cljs.tools/reader reads a string and attempts to convert it into a primative type. i.e. "1234" becomes 1234.

2017-03-20 09:17 UTC, axrs commented on src/cljs/centrebull/competitions/core.cljs
> +    [cljs.spec :as s]))
clojure.spec and cljs.spec resolve the same namespace by the compiler

2017-03-20 09:18 UTC, axrs commented on src/cljs/centrebull/shooters/view.cljs
> +        [:div {:local "1/3"} (if (empty? preferred-name) (str first-name " " last-name) preferred-name)]
That's fine. Mabe move the calculated field of first-name + last-name into a let statement above.

2017-03-20 09:23 UTC, axrs requested changes

2017-03-20 09:23 UTC, axrs commented on src/cljc/centrebull/spec.cljc
> +(defn- str->int [s] #?(:cljs (cond (and (string? s) #(not= "" %)) s
Have a go at fixing this. It should just be requiring reader.

2017-03-21 04:45 UTC, CalebMacdonaldBlack commented
@axrs

2017-03-21 09:52 UTC, axrs requested changes

2017-03-21 09:52 UTC, axrs commented on src/cljs/centrebull/shooters/view.cljs
> +       (let [full-name (str first-name " " last-name)]
```
(let [name (or preferred-name (str first-name " " last-name))]
...
)
```

2017-03-21 09:52 UTC, axrs commented on src/cljc/centrebull/spec.cljc
> +(defn- str->int [s] #?(:cljs (cond (and (string? s) #(not= "" %)) (clojure.tools.reader/read-string s)
Is clojure.tools.reader available in cljs?

2017-03-21 09:52 UTC, axrs commented
@CalebMacdonaldBlack Conflicts

2017-03-21 10:17 UTC, CalebMacdonaldBlack commented
@axrs

2017-03-22 08:41 UTC, CalebMacdonaldBlack commented
@axrs

2017-03-22 09:09 UTC, axrs approved these changes

2017-03-22 09:09 UTC, merged