cb-103
axrs/centrebull pull request #93
Opened 2017-05-14 21:56 UTC by axrs

2017-05-14 23:06 UTC, CalebMacdonaldBlack requested changes

2017-05-14 23:06 UTC, CalebMacdonaldBlack commented on src/cljs/centrebull/shooters/view.cljs
> +                 {:id "FSA" :name "FSA"}
Will the translate grade function still work with this change?
```(defn- translate-grade [g]
  (cond
    (= "A" g) "10"
    (= "B" g) "09"
    (= "C" g) "08"
    (= "D" g) "07"
    (= "FS" g) "06"
    (= "FS1" g) "05"
    (= "FS2" g) "04"
    (= "FO" g) "03"
    (= "FO1" g) "02"
    (= "FO2" g) "01"
    :else "00"))

2017-05-14 23:20 UTC, axrs commented
Good catch. The answer would be no

--------------------
Alex Scott

Email: xander@cadcoder.com

LinkedIn: https://au.linkedin.com/in/alexanderrscott

GitHub: https://github.com/axrs
BitBucket: https://bitbucket.org/axrs


On 15 May 2017 9:06 am, "Caleb Macdonald Black" <notifications@github.com>
wrote:

> *@CalebMacdonaldBlack* requested changes on this pull request.
> ------------------------------
>
> In src/cljs/centrebull/shooters/view.cljs
> <https://github.com/axrs/centrebull/pull/93#discussion_r116393128>:
>
> > @@ -11,8 +11,9 @@
>                   {:id "B" :name "B"}
>                   {:id "C" :name "C"}
>                   {:id "FO" :name "FO"}
> -                 {:id "FS1" :name "FS1"}
> -                 {:id "FS2" :name "FS2"}])
> +                 {:id "FSA" :name "FSA"}
>
> Will the translate grade function still work with this change?
>
>   (cond
>     (= "A" g) "10"
>     (= "B" g) "09"
>     (= "C" g) "08"
>     (= "D" g) "07"
>     (= "FS" g) "06"
>     (= "FS1" g) "05"
>     (= "FS2" g) "04"
>     (= "FO" g) "03"
>     (= "FO1" g) "02"
>     (= "FO2" g) "01"
>     :else "00"))
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/axrs/centrebull/pull/93#pullrequestreview-38010787>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAjZrsL6IJgkYrkI4iBMf8yrXBbm-WJVks5r54jpgaJpZM4NahMt>
> .
>

2017-05-17 08:36 UTC, CalebMacdonaldBlack approved these changes

2017-05-17 08:40 UTC, merged